Сервер статистики
SugarFoxy/java-explore-with-me pull request #1
Opened 2023-02-22 09:52 UTC by SugarFoxy

2023-02-23 10:15 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть несколько замечаний, которые необходимо исправить!

Желаю удачи!!!

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-dto/src/main/java/ru/practicum/explore/dto/HitDto.java
> +@Builder
Точно все аннотации нужны?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-dto/src/test/java/ru/practicum/explore/dto/HitDtoTest.java
> +    private JacksonTester<HitDto> jtHitDto;
не нужны модификаторы в тестах

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-dto/src/test/java/ru/practicum/explore/dto/HitDtoTest.java
> +    ObjectMapper objectMapper;
Зачем тебе `ObjectMapper`, как поле, если ты им нигде не пользуешься?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-dto/src/test/java/ru/practicum/explore/dto/HitDtoTest.java
> +        assertThat(itemDtoResult).extractingJsonPathValue("$.timestamp").isEqualTo(hitDto.getTimestamp());
очень длинные строки, тяжело их читать, и мне, и потом работать с ними тоже.

обычно в такой ситуации делают перенос по каждой из точек "первого уровня". Примерно так:

```java
assertThat(itemDtoResult)
    .extractingJsonPathNumberValue("$.id")
    .isEqualTo(hitDto.getId().intValue());
```

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-dto/src/test/java/ru/practicum/explore/dto/StatsDtoTest.java
> +import java.io.IOException;
Этот импорт точно нужен?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-dto/src/test/java/ru/practicum/explore/dto/StatsDtoTest.java
> +class StatsDtoTest {
Замечания, аналогичные `HitDtoTest`

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/explore/stats/controller/StatsController.java
> +            @RequestParam(required = false, defaultValue = "false") boolean unique
если используешь `defaultValue`, то нет необходимости в `required`

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/explore/stats/service/StatsServiceImp.java
> +                    .flatMap((url) -> storage.getStats(parsStart, parsEnd, url, unique).stream())
скобки около `url` точно нужны?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/explore/stats/storage/StatsStorageImp.java
> +        }
```java
cr.multiselect(root.get("app"), root.get("uri"), unique ? cb.countDistinct(root.get("ip")) : cb.count(root));
```

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/test/java/ru/practicum/explore/ExploreTests.java
> +//}
Этот файл зачем?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/main/resources/schema.sql
> +    ip         VARCHAR(1024)                           NOT NULL,
зачем под `ip` так много символов?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/test/java/ru/practicum/explore/hit/mapper/HitMapperTest.java
> +    HitDto hitDto = HitDto.builder()
Зачем поле класса заводить?
Может локальной переменной можно обойтись?

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/test/java/ru/practicum/explore/stats/controller/StateControllerTest.java
> +    private MockMvc mockMvc;
модификатор не нужен

2023-02-23 10:15 UTC, LexLippi commented on stats-service/stats-server/src/test/java/ru/practicum/explore/stats/storage/StatsStorageImpTest.java
> +    private EntityManager entityManager;
модификаторы не нужны

2023-02-23 10:15 UTC, LexLippi commented on stats-util/src/main/java/ru/practicum/util/DateTimeUtils.java
> +    public static LocalDateTime parseDate(String dateString) {
можно просто `date`, там по типу данных видно, что это `String`

2023-02-23 10:15 UTC, LexLippi commented on stats-util/src/main/java/ru/practicum/util/exception/BadRequestException.java
> +//    } пригодиться в будущем
Тут три строки кода, которые на самом деле почти полная копипаста метода ниже, может всё-таки удалим?)

2023-02-23 10:43 UTC, SugarFoxy commented on stats-service/stats-dto/src/main/java/ru/practicum/explore/dto/HitDto.java
> +@Builder
Ах если бы я знала что ждет меня в будущем. Конструктор со всеми значениями пока(а может и вовсе) не нужен

2023-02-23 10:59 UTC, SugarFoxy commented on stats-service/stats-dto/src/main/java/ru/practicum/explore/dto/HitDto.java
> +@Builder
а нет нужно)))) билдер без этого конструктора жить не может

2023-02-23 11:14 UTC, SugarFoxy commented on stats-service/stats-server/src/main/java/ru/practicum/explore/stats/storage/StatsStorageImp.java
> +        }
логично))))

2023-02-23 11:16 UTC, SugarFoxy commented on stats-service/stats-server/src/test/java/ru/practicum/explore/ExploreTests.java
> +//}
Пережиток экспериментов

2023-02-24 14:10 UTC, LexLippi approved these changes
Привет, отличная работа.

Есть пара замечаний, их можно к следующей итерации поправить!

Желаю удачи!!!

2023-02-24 14:10 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/explore/stats/storage/StatsStorageImp.java
> +                    cb.lessThanOrEqualTo(root.get("timestamp"), end)
Кстати, вместо этого можно `between`, он тоже самое делает

2023-02-24 14:10 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/explore/stats/storage/StatsStorageImp.java
> +                    cb.lessThanOrEqualTo(root.get("timestamp"), end),
тоже можно на `between` заменить

2023-02-24 14:10 UTC, LexLippi commented on stats-service/stats-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS hit
Вот это странные команды вместе.

`DROP TABLE IF EXISTS hit` гарантирует тебе, что таблицы `hit` нет, даже если она была.
А потом ты делаешь `CREATE TABLE IF NOT EXISTS hit`, хотя она точно не существует :)

2023-02-26 10:13 UTC, merged