Main svc
SugarFoxy/java-explore-with-me pull request #2
Opened 2023-03-07 19:02 UTC by SugarFoxy

2023-03-08 18:35 UTC, LexLippi requested changes
Привет, отличная работа!

Есть некоторое количество комментариев, которые надо исправить.

Желаю удачи!!!

2023-03-08 18:35 UTC, LexLippi commented on stats-service/stats-client/src/main/java/ru/practicum/explore/StatsClient.java
> +        String end = DateTimeUtils.getDateTime(LocalDateTime.now().plusSeconds(10));
А почему тут какие-то константы используются непонятного происхождения?

2023-03-08 18:35 UTC, LexLippi commented on stats-service/stats-client/src/main/java/ru/practicum/explore/StatsClient.java
> +            if (statsArray.size() == 0) {
1. Лучше `statsArray.isEmpty()`
2. А почему здесь не пустой `Optional`, а  содержащий 0?

2023-03-08 18:35 UTC, LexLippi commented on stats-service/stats-client/src/main/java/ru/practicum/explore/StatsClient.java
> +        return Optional.empty();
лучше воспользоваться Stream API. Это существенно бы сократило код и повысило его читаемость, но если не получится, то не обязательно переделывать

2023-03-08 18:35 UTC, LexLippi commented on stats-service/stats-client/src/main/java/ru/practicum/explore/StatsClient.java
> +    public Map<Long, Long> viewsMapRequest(List<Long> eventIds) {
Вопросы те же, что и к методу выше

2023-03-08 18:35 UTC, LexLippi commented on stats-util/src/main/java/ru/practicum/util/exception/ConflictException.java
> +package ru.practicum.util.exception;
Это лучше в `stats-service` перенести

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS compilation_events,compilations,requests,events,categories,users;
Сочетание `drop table`, а потом оператора `if not exists` у таблиц - странное.
Плюс не хочется при каждом релизе приложения терять данные, может возможно обойтись без этого?

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +    email VARCHAR(512)                            NOT NULL,
В стандарте написано, что длина `email` не превышает 320 символов, тогда и нам больше не надо.
Вот здесь написано:

https://www.rfc-editor.org/errata/eid1690

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/events/event/storage/EventRepositoryCustomImpl.java
> +        Root<Event> eventRoot = q.from(Event.class);
Лучше называть это `builder`, `query`, иначе взаимодействовать потом с этим будет сложно

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/events/event/storage/EventRepositoryCustomImpl.java
> +                    cb.greaterThan(eventRoot.get("participant_limit"), eventRoot.get("confirmed_requests"))));
Фигурные скобки советую ставить всегда, в соответствии с `Java Google Code Style`:

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/events/event/storage/EventRepositoryCustom.java
> +                                            LocalDateTime rangeStart, LocalDateTime rangeEnd, int from, int size);
Когда параметров много, можно подумать о создании объекта для их передачи

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/category/controller/ControllerPublicCategory.java
> +            @RequestParam(required = false, defaultValue = "10") Integer size) {
Если есть `defaultValue`, то в `required` нет необходимости

2023-03-08 18:35 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/events/event/controller/ControllerAdminEvent.java
> +                                      @Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
`name`, если совпадает с названием локальной переменной, то можно не писать

2023-03-08 19:35 UTC, SugarFoxy commented on stats-service/stats-client/src/main/java/ru/practicum/explore/StatsClient.java
> +        String end = DateTimeUtils.getDateTime(LocalDateTime.now().plusSeconds(10));
Не работал метод пыталась разобраться дело во времени или нет, оказалась проблема в приходящем uri. Ну а обратно поправить конечно забыла))). Ты как орел найдешь даже маленькие неточности =D

2023-03-08 20:06 UTC, SugarFoxy commented on main-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS compilation_events,compilations,requests,events,categories,users;
не хочется при каждом запуске приложения дропать таблицы руками. Поэтому и сделана такая конструкция. Могу ее удалять при отправке в гит.

2023-03-08 20:12 UTC, SugarFoxy commented on main-service/src/main/java/ru/practicum/events/event/storage/EventRepositoryCustomImpl.java
> +                    cb.greaterThan(eventRoot.get("participant_limit"), eventRoot.get("confirmed_requests"))));
вывод надо писать сразу правильно что бы не забывать все поправить

2023-03-10 07:42 UTC, LexLippi approved these changes
Привет.

Отличная работа!

Желаю удачи при реализации последней работы в Практикуме!

2023-03-10 09:37 UTC, merged